# SPDX-FileCopyrightText: 2023 Havs- och vattenmyndigheten
#
# SPDX-License-Identifier: MIT
repos:
- repo: https://github.com/gitleaks/gitleaks
  rev: 43fae355e6fe4d99d2a7b240a224b85e2903aeb4 #v8.21.2
  hooks:
  - id: gitleaks
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: cef0300fd0fc4d2a87a85fa2093c6b283ea36f4b #v5.0.0
  hooks:
  - id: end-of-file-fixer
  - id: trailing-whitespace
  - id: check-yaml
  - id: check-json
